finalproject/finalproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from restaurant import views as rest_views

urlpatterns = [
    url(r'^', include('restaurant.urls')),
    url(r'^menu/', include('menu.urls',namespace="menu")),
    url(r'^login/', rest_views.login_view, name='Login'),
    url(r'^logout/', rest_views.logout_view, name='Logout'),
    url(r'^admin/', admin.site.urls)
]

finalproject/menu/urls.py
from django.conf.urls import url
from django.conf.urls import include, url
from . import views


from .views import (
        post_delete,
        )

app_name = 'menu'
urlpatterns = [
    url(r'^$', views.viewmenu, name='viewmenu'),
    url(r'^(?P<menu_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<menu_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^post/$', views.post, name='update'),
    url(r'^post/(?P<pk>\d+)/$', views.detail, name='detail'),
    #new information here
    url(r'^new/$', views.specialviewmenu, name='specialviewmenu'),
    url(r'^postnew/$', views.specialpost, name='specialupdate'),
    url(r'^postnew/(?P<pk>\d+)/$', views.specialdetail, name='specialdetail'),
    url(r'^manager$', views.managerview, name='managerview'),
    #SUREVEY URLS
    url(r'^survey/$', views.viewsurvey, name='survey'),
    url(r'^surveynew/$', views.viewpost, name='surveyupdate'),
    url(r'^survey/(?P<question_id>[0-9]+)/$', views.viewdetail, name='surveydetail'),
]

finalproject/restaurant/urls.py
from django.conf.urls import url
from . import views

app_name = 'restaurant'
urlpatterns = [
    url(r'^$', views.home, name='home'),
	url(r'^guest-user/$', views.TableIDVerification, name='Guest User'),
	url(r'^guest-user/tryagain$', views.TryAgain, name='tryagain'),
	url(r'^order-placed/$', views.orderplaced, name='OrderPlaced'),
	url(r'^contact-server/$', views.ContactServer, name='ContactServer'),
	url(r'^contact-server-sent/$', views.ContactServerSent, name='ContactServerSent'),
    url(r'^server/$', views.ServerView.as_view(), name='server'),
    url(r'^server/orderstart$', views.StartOrder, name='orderstart'),
    url(r'^gateway/(\w+)/$', views.gateway, name='gateway'),
    url(r'^server/orders$', views.OrderView.as_view(), name='orders'),
    url(r'^server/(?P<order_id>[0-9]+)/orderdetails$', views.orderdetail, name='orderdetails'),
    url(r'^server/(?P<pk>[0-9]+)/alertdetails$', views.AlertDetailView.as_view(), name='alertdetails'),
    url(r'^(?P<alert_id>[0-9]+)/resolveAlert/$', views.resolveAlert, name='resolveAlert'),
    url(r'^kitchen/$', views.KitchenView.as_view(), name='kitchen'),
    url(r'^kitchen/kitchendetail/(?P<order_id>[0-9]+)$', views.kitchendetail, name='kitchendetail'),
	
	url(r'^order-menu/$', views.MenuView.as_view(), name='Menu'),
	url(r'^(?P<pk>[0-9]+)/additem/$', views.AddItem, name='additem'),
	url(r'^login/$', views.login_view, name='Login'),
	url(r'^server/$', views.StartOrder, name='server'),
	url(r'^server/orders$', views.OrderView.as_view(), name='orders'),
	url(r'^server/(?P<pk>[0-9]+)/orderdetails$', views.OrderDetailView.as_view(), name='orderdetails'),
    url(r'^createaccount/$', views.createaccount),
    url(r'^payment/$', views.payment, name='payment'),
]

finalproject/menu/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.db import models


class menu(models.Model):
  
    Name = models.CharField(max_length=200)
    Description = models.CharField(max_length=200)
    Nutrition = models.CharField(max_length=200)
    Price = models.IntegerField(default=170)
class specialmenu(models.Model):
    Name = models.CharField(max_length=200)
    Description = models.CharField(max_length=200)
    Nutrition = models.CharField(max_length=200)
    Price = models.IntegerField(default=170)
class survey(models.Model):
    question = models.CharField(max_length=200)
    score = models.IntegerField(default=0)
class choice(models.Model):
    question = models.ForeignKey(survey, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    

finalproject/restaurant/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from menu.models import menu

class Table (models.Model):
	Table = models.IntegerField(default=0)
	Code = models.CharField(max_length=20)

class Restaurant (models.Model):
    Name = models.CharField(max_length=100)
    Location = models.CharField(max_length=100)

class Order(models.Model):
    CREATED = 'CREATED'
    SENT_TO_KITCHEN = 'SENT TO KITCHEN'
    STARTED = 'STARTED'
    READY = 'READY'
    SERVED = 'SERVED'
    COMPLETED = 'COMPLETED'
    STATUS_CHOICES = (
        (CREATED, 'Order created'),
        (SENT_TO_KITCHEN, 'Order sent to kitchen'),
        (STARTED, 'Order started'),
        (READY, 'Order ready to be served'),
        (SERVED, 'Order served'),
        (COMPLETED, 'Order completed')
    )
    Code = models.CharField(max_length=20)
    Table = models.IntegerField(default=0)
    Restaurant = models.ForeignKey(Restaurant, default=1)
    Status= models.CharField(max_length=15, choices=STATUS_CHOICES, default=CREATED,)
    StartTime = models.DateTimeField(default=timezone.now)

class Alert(models.Model):
    Order = models.ForeignKey(Order)
    Message = models.CharField(max_length=500)
    Resolved = models.BooleanField(default=0)

class UserType(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    is_customer = models.BooleanField(default=True)
    is_kitchen = models.BooleanField(default=False)
    is_server = models.BooleanField(default=False)
    restaurant = models.ForeignKey(Restaurant, blank=True, null=True)
    # Override the __unicode__() method to return something meaningful!
    def __unicode__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_usertype(sender,instance,created, **kwargs):
	if created:
		UserType.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_usertype(sender,instance,created, **kwargs):
	if created:
		instance.usertype.save()

class OrderedMenuItems(models.Model):
	order_id = models.ForeignKey(Order)
	#table_id = models.ForeignKey(Order)
	item_name = models.ForeignKey(menu, null=True)
	num_items = models.IntegerField(default=0)
	notes = models.TextField(max_length=500, null=True)
	#def __str__(self):
		#return self.item_name
		#return self.item_name

class Payment(models.Model):
	pay_id = models.ForeignKey(Order)
	total = models.PositiveIntegerField(default=0)
	def __str__(self):
		return self.pay_id

finalproject/menu/forms.py
from django import forms
from .models import menu
from .models import specialmenu
from .models import survey

class UserForm(forms.ModelForm):
    class Meta:
        model = menu
        fields = ['Name', 'Description','Nutrition', 'Price']
class specialUserForm(forms.ModelForm):
    class Meta:
        model = specialmenu
        fields = ['Name', 'Description','Nutrition', 'Price']
class customersurvey(forms.ModelForm):
    class Meta:
        model = survey
        fields = ['question', 'score']

finalproject/restaurant/forms.py
from django import forms
from .models import Order, Alert, OrderedMenuItems
from django.contrib.admin import widgets
from menu.models import menu
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class TableIDForm(forms.ModelForm):
	class Meta:
		model = Order
		fields = ('Code',)
	#code_id = forms.CharField(label = 'Code ID', max_length = 64)
	widgets = {
		#'tableID': forms.TextInput(
			#attrs={'placeholder': 'TableID', 'class':'form-control'}
		#),
		'code_id': forms.TextInput(
			attrs={'placeholder': 'code_id', 'class':'form-control'}
		),
	}

class OrderForm(forms.ModelForm):
	class Meta:
		model = menu
		fields = ('Name', 'Description', 'Nutrition', 'Price')

	Name = forms.CharField(label="Name", required=True)
	Description = forms.CharField(label="Description")
	Nutrition = forms.CharField(label="Nutrition")
	Price = forms.IntegerField(label="Price")

class ItemForm(forms.ModelForm):

    class Meta:
        model = OrderedMenuItems
        fields = ('num_items', 'notes')
        exclude = ('order_id', 'item_name')

    #order_id = forms.ModelChoiceField(queryset=Order.objects.all() , label="Code", required=True)#, readonly:True)#, disabled=True)
    #item_name = forms.ModelChoiceField(queryset=menu.objects.all(), label="Menu Item")#, required=True)
    num_items = forms.IntegerField(min_value=0, initial=0, label = "Number of items", required=False)
    notes = forms.CharField(label="Notes", required=False, widget=forms.Textarea)

class OrderStartForm(forms.Form):
    Code = forms.CharField(label = 'Code', max_length=10, required=True)
    Table = forms.IntegerField(min_value=1, initial=1, label = 'Table', required=True)

class KitchenForm(forms.ModelForm):
	class Meta:
		model = Order
		fields = ('Status',)

class LoginForm(forms.Form):
    username = forms.CharField(label='User Name', max_length=64)
    password = forms.CharField(widget=forms.PasswordInput())

class ContactServerForm(forms.ModelForm):
	class Meta:
		model = Alert
		fields = ('Message',)
		exclude = ('Order', 'Resolved',)
	Message = forms.CharField(label="Message", required=False, widget=forms.Textarea)

class AlertForm(forms.Form):
    Order = forms.IntegerField(label = 'Order', required=True)
    Message = forms.CharField(label = 'Message')
    Resolved = forms.BooleanField(label = 'Resolved')

class CreateAccountForm(UserCreationForm):
	username = forms.CharField(required = True)
	first_name = forms.CharField(required = True)
	last_name = forms.CharField(required = True)
	email = forms.EmailField(required = True)
	
	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
		
	def save(self, commit = True):
		user = super(CreateAccountForm, self).save(commit = False)
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.email = self.cleaned_data['email']
		
		if commit:
			user.save()
			
		return user

finalproject/menu/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.template import loader
from django.http import Http404
from django.shortcuts import get_object_or_404, render

# Create your views here.
from django.http import HttpResponse
from .models import menu
from .models import specialmenu
from .forms import specialUserForm
import datetime

def viewmenu(request):
    latest_menu_list = menu.objects.order_by('-id')[:1000]
    template = loader.get_template('menu/index.html')
    context = {
        'latest_menu_list': latest_menu_list,
    	}
    return HttpResponse(template.render(context, request))
    
def detail(request, menu_id):
    question = get_object_or_404(menu, pk=menu_id)
    return render(request, 'menu/detail.html', {'question': question})


def results(request, menu_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % menu_id)

def display(request):
  return render_to_response('index.html', {'obj': models.menu.objects.all()})

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import View
from .models import menu as Users
from .forms import UserForm
from django.shortcuts import redirect
from .models import menu


def post(request):
        
        if request.method == "POST":
                form = UserForm(request.POST)
                if form.is_valid():
                    latest_menu_list = menu.objects.order_by('-id')[:1000]
                    post = form.save(commit=False)
                    post.save()
                    context ={'latest_menu_list': latest_menu_list,}
                    return render(request, "menu/index.html",context)
        else:
                form = UserForm()
                
        return render(request, 'menu/update.html', {'form': form})
        
    
        
def post_delete(request, menu_id):
        instance=get_object_or_404(menu, pk=menu_id)
        instance.deleted()
        messages.success(request, "succesfully deleted")
        #return redirect('detail',pk=post.pk)


### SPECIAL MENU CODE SECTION

def specialviewmenu(request):
    latest_menu_list = specialmenu.objects.order_by('-id')[:1000]
    template = loader.get_template('menu/specialindex.html')
    context = {
        'latest_menu_list': latest_menu_list,
        }
    return HttpResponse(template.render(context, request))
    
def specialdetail(request, menu_id):
    question = get_object_or_404(menu, pk=_id)
    return render(request, 'menu/specialdetail.html', {'question': question})


def specialresults(request, menu_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % menu_id)

def specialdisplay(request):
  return render_to_response('specialindex.html', {'obj': models.specialmenu.objects.all()})

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import View
from .models import menu as Users
from .forms import UserForm
from django.shortcuts import redirect
from .models import menu


def specialpost(request):
        
        if request.method == "POST":
                form = specialUserForm(request.POST)
                if form.is_valid():
                    latest_menu_list = specialmenu.objects.order_by('-id')[:1000]
                    post = form.save(commit=False)
                    post.save()
                    context ={'latest_menu_list': latest_menu_list,}
                    return render(request, "menu/specialindex.html",context)
        else:
                form = specialUserForm()
                
        return render(request, 'menu/specialupdate.html', {'form': form})
        
    
        
def specialpost_delete(request, menu_id):
        instance=get_object_or_404(menu, pk=menu_id)
        instance.deleted()
        messages.success(request, "succesfully deleted")
        #return redirect('detail',pk=post.pk)

#    response = "You're looking at the results of question %s."
#    return HttpResponse(response % menu_id)

#open dashboard for manager
def managerview(request):
    template = loader.get_template('menu/welcome.html')
    return render(request, "menu/welcome.html", {'time' : datetime.datetime.now()})

## CUSTOMER SURVEYYY##############

from .models import survey
from .forms import customersurvey
def viewsurvey(request):
    latest_menu_list1 = survey.objects.order_by('-id')[:1000]
    template = loader.get_template('menu/survey.html')
    context = {
        'latest_menu_list1': latest_menu_list1,
        }
    return HttpResponse(template.render(context, request))
    
def viewdetail(request, menu_id):
    question = get_object_or_404(menu, pk=menu_id)
    return render(request, 'menu/surveydetail.html', {'question': question})


def viewresults(request, menu_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % menu_id)

def viewdisplay(request):
  return render_to_response('survey.html', {'obj': models.menu.objects.all()})

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import View
from .models import menu as Users
from .forms import UserForm
from django.shortcuts import redirect
from .models import menu


def viewpost(request):
        
        if request.method == "POST":
                form = customersurvey(request.POST)
                if form.is_valid():
                    latest_menu_list = survey.objects.order_by('-id')[:1000]
                    post = form.save(commit=False)
                    post.save()
                    context ={'latest_menu_list1': latest_menu_list,}
                    return render(request, "menu/survey.html",context)
        else:
                form = customersurvey()
                
        return render(request, 'menu/surveyupdate.html', {'form': form})
        
    
        
def post_delete(request, menu_id):
        instance=get_object_or_404(menu, pk=menu_id)
        instance.deleted()
        messages.success(request, "succesfully deleted")
        #return redirect('detail',pk=post.pk)

finalproject/restaurant/templates/restaurant/TableIDVerificationForm.html
{% extends 'restaurant/homebase.html' %}
{% load static %}
{% block content %}

<body class="login-page">
	<nav class="navbar navbar-primary navbar-transparent navbar-absolute">
    	<div class="container">
        	<!-- Brand and toggle get grouped for better mobile display -->
        	<div class="navbar-header">
        		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example">
            		<span class="sr-only">Toggle navigation</span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
        		</button>
        		<a class="navbar-brand" href="/">Raccoon Express</a>
        	</div>

        	<div class="collapse navbar-collapse" id="navigation-example">
        		<ul class="nav navbar-nav navbar-right">

							<li>
                <a href="/login">
                  <i class="material-icons">lock_open</i>Log in
                </a>
              </li>

              <li>
                <a href="/createaccount">
                  <i class="material-icons">assignment</i>Sign up
                </a>
              </li>

        		</ul>
        	</div>
    	</div>
    </nav>

	<div class="page-header header-filter" style="background-image: url('{% static "restaurant/img/loginbg.jpg" %}'); background-size: cover; background-position: top center;">
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
					<div class="card card-signup">
						<form class="form" id="TableIDForm" method="post" action="">
							<div class="header header-primary text-center">
								<h4 class="card-title">Guest Ordering</h4>

							</div>
							  <p class="description text-center">Obtain your code for ordering from the waiter!</p>
                <br/><br/>
              <div class="content text-center">
								{% csrf_token %}

								<p>Code*:	{{ form.Code }}</p>
								{% if form.errors %}
									{{ form.Code.errors }}
								{% endif %}

								<input id="code-submit" class="btn btn-primary" type="submit" value="Submit"/>

							</div>
							<div class="footer text-center">
								<a href="#pablo" class="btn btn-primary btn-simple btn-wd btn-lg">Need Help?</a>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
{% endblock %}

finalproject/restaurant/templates/restaurant/additem.html
{% load static %}

<h1> Add Item </h1>

<p> Menu Item: {{request.session.Name}} </p>
<p> {{request.session.Description}} - {{request.session.Price}} </p>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Add to Order">
</form>

<a href="{% url 'restaurant:Menu' %}">Return to Menu</a>

finalproject/restaurant/templates/restaurant/alertdetail.html
<h1> Alert Details </h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<p> Table #{{ alert.Order.Table }}</p>
<p> Message: {{alert.Message}}</p>

<form action="{% url 'restaurant:resolveAlert' alert.id %}" method="post">
{% csrf_token %}
<input type="submit" value="Resolve" />
</form>

finalproject/restaurant/templates/restaurant/createaccount.html
{% extends 'restaurant/homebase.html' %}
{% load static %}
{% block content %}

<body class="login-page">
	<nav class="navbar navbar-primary navbar-transparent navbar-absolute">
    	<div class="container">
        	<!-- Brand and toggle get grouped for better mobile display -->
        	<div class="navbar-header">
        		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example">
            		<span class="sr-only">Toggle navigation</span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
        		</button>
        		<a class="navbar-brand" href="/">Raccoon Express</a>
        	</div>

        	<div class="collapse navbar-collapse" id="navigation-example">
        		<ul class="nav navbar-nav navbar-right">

              <li>
                <a href="#">
                  <i class="material-icons">assignment</i> sign up
                </a>
              </li>

        		</ul>
        	</div>
    	</div>
    </nav>

	<div class="page-header header-filter" style="background-image: url('{% static "restaurant/img/loginbg.jpg" %}'); background-size: cover; background-position: top center;">
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
					<div class="card card-signup">
						<form class="form" method="post" action=".">
							<div class="header header-primary text-center">
								<h4 class="card-title">Sign Up</h4>
								<div class="social-line">
									<a href="#pablo" class="btn btn-just-icon btn-simple">
										<i class="fa fa-facebook-square"></i>
									</a>
									<a href="#pablo" class="btn btn-just-icon btn-simple">
										<i class="fa fa-twitter"></i>
									</a>
									<a href="#pablo" class="btn btn-just-icon btn-simple">
										<i class="fa fa-google-plus"></i>
									</a>
								</div>
							</div>
							  <p class="description text-center">Welcome to Raccoon Express - Please Sign Up</p>
                <br/><br/>
              <div class="content text-center">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="btn btn-primary " type="submit" value="Submit" />

							</div>
							<div class="footer text-center">
								<a href="#pablo" class="btn btn-primary btn-simple btn-wd btn-lg">forgot password?</a>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
{% endblock %}

finalproject/restaurant/templates/restaurant/createaccount_successful.html
{% extends 'restaurant/homebase.html' %}
{% load static %}
{% block content %}

<body class="login-page">

	<div class="page-header header-filter" style="background-image: url('{% static "restaurant/img/signupbg.jpg" %}'); background-size: cover; background-position: top center;">
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
					<div class="card card-signup">
              <div class="content text-center">
                <h1>Your Account Was Successfully Created</h1>
							</div>
							<div class="footer text-center">
								<a href="/login" class="btn btn-primary btn-simple btn-wd btn-lg">LOG IN</a>
                <a href="/" class="btn btn-primary btn-simple btn-wd btn-lg">HOME</a>
							</div>
					</div>
				</div>
			</div>
		</div>

{% endblock %}

finalproject/restaurant/templates/restaurant/orders.html
{% extends 'restaurant/gatewaybase.html' %}
{% load static %}
{% block content %}
  <!-- based on gatewaybase.html
      functionality:
      1. profile page
      2. permission grabber-->
  <body>
  {% if user.is_authenticated %}
  <div class="wrapper">
      <div class="sidebar" data-active-color="rose" data-background-color="black">
          <div class="logo">
              <a href="." class="simple-text">
                  Raccoon Express
              </a>
          </div>
          <div class="logo logo-mini">
              <a href="/" class="simple-text">
                  Home
              </a>
          </div>
          <div class="sidebar-wrapper">
              <div class="user">
                  <div class="photo">
                      <img src="{% static "restaurant/img/faces/avatar.jpg" %}" />
                  </div>
                  <div class="info">
                      <a data-toggle="collapse" href="#collapseExample" class="collapsed">
                          {{ username }}
                          <b class="caret"></b>
                      </a>
                      <div class="collapse" id="collapseExample">
                          <ul class="nav">
                              <li>
                                  <a href="#">My Profile</a>
                              </li>
                              <li>
                                  <a href="#">Edit Profile</a>
                              </li>
                          </ul>
                      </div>
                  </div>
              </div>

              <ul class="nav">
  								<li class="active">
  									<a href="/server">
  											<i class="material-icons">room_service</i>
  											<p>Waiter</p>
  										</a>
  									</li>
              </ul>

          </div>
      </div>
      <div class="main-panel">
          <nav class="navbar navbar-transparent navbar-absolute">
              <div class="container-fluid">
                  <div class="navbar-minimize">
                      <button id="minimizeSidebar" class="btn btn-round btn-white btn-fill btn-just-icon">
                          <i class="material-icons visible-on-sidebar-regular">more_vert</i>
                          <i class="material-icons visible-on-sidebar-mini">view_list</i>
                      </button>
                  </div>
                  <div class="navbar-header">
                      <button type="button" class="navbar-toggle" data-toggle="collapse">
                          <span class="sr-only">Toggle navigation</span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                      </button>
                      <a class="navbar-brand" href="#"> . </a>
                  </div>
                  <div class="collapse navbar-collapse">
                      <ul class="nav navbar-nav navbar-right">
                          <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                  <i class="material-icons">notifications</i>
                                  <span class="notification">{{current_alert_list.count}}</span>
                                  <p class="hidden-lg hidden-md">
                                      Notifications
                                      <b class="caret"></b>
                                  </p>
                              </a>
                              <ul class="dropdown-menu">
                                {% if current_alert_list %}
                                    {% for alert in current_alert_list %}
                                    <li><a href="{% url 'restaurant:alertdetails' alert.id %}">Table #{{ alert.Order.Table }} - {{alert.Message}}</a></li>
                                    {% endfor %}
                                {% else %}
                                    <li><a href="">No current alerts</a></li>
                                {% endif %}
                              </ul>
                          </li>

                          <li "dropdown">
                              <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                  <i class="material-icons">person</i>
                                  <p class="hidden-lg hidden-md">Profile</p>
                              </a>
                              <ul class="dropdown-menu">
                                  <li>
                                      <a href="/logout">Sign Out</a>
                                  </li>
                              </ul>
                          </li>

                          <li class="separator hidden-lg hidden-md"></li>
                      </ul>
                      <form class="navbar-form navbar-right" role="search">
                          <div class="form-group form-search is-empty">
                              <input type="text" class="form-control" placeholder="Search">
                              <span class="material-input"></span>
                          </div>
                          <button type="submit" class="btn btn-white btn-round btn-just-icon">
                              <i class="material-icons">search</i>
                              <div class="ripple-container"></div>
                          </button>
                      </form>
                  </div>
              </div>
          </nav>


  <!--Main Content starts here -->

          <div class="content">
              <div class="container-fluid">
  							<div class="row">     <!-- Row1 Start-->

                  <div class="col-md-4 ">
                    <div class="card">
                      <div class="card-header card-header-icon" data-background-color="orange">
                        <i class="material-icons">assignment</i>
                      </div>
                      <div class="card-content">
                        <h4 >Existing Orders</h4>
                        {% if latest_order_list %}
                            <ul>
                            {% for order in latest_order_list %}
                                <li><a href="{% url 'restaurant:orderdetails' order.id %}">Table: {{ order.Table }}</a></li>
                            {% endfor %}
                            </ul>
                        {% else %}
                            <p>No current orders</p>
                        {% endif %}
                       </div>
                    </div>
                  </div>

                  <div class="col-md-4">
                    <div class="card">
                      <div class="card-header card-header-icon" data-background-color="green">
                        <i class="material-icons">room_service</i>
                      </div>
                      <div class="card-content">
                        <h4 >New Order</h4>
                        <a class="cardtitle" href="{% url 'restaurant:orderstart' %}">Create</a>
                       </div>
                    </div>
                  </div>

              </div>    <!-- Row1 End-->
            </div>
          </div>


          <footer class="footer">
              <div class="container-fluid">
                  <nav class="pull-left">
                      <ul>
                          <li>
                              <a href="/">
                                  Home
                              </a>
                          </li>
                          <li>
                              <a href="#">
                                 About Us
                              </a>
                          </li>
                          <li>
                              <a href="/login">
                                 Restaurant login
                              </a>
                          </li>
                  </nav>
                  <p class="copyright pull-right">
                      &copy;
                      <script>
                          document.write(new Date().getFullYear())
                      </script>
                      Made by the most awesome Group 4
                  </p>
              </div>
          </footer>
      </div>
  </div>
    {% else %}
      <h1><a href="/login">Please Login</a></h1>
    {% endif %}
  </body>
  {% endblock %}