finalproject/finalproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from restaurant import views as rest_views

urlpatterns = [
    url(r'^', include('restaurant.urls')),
    url(r'^menu/', include('menu.urls',namespace="menu")),
    url(r'^login/', rest_views.login_view, name='Login'),
    url(r'^logout/', rest_views.logout_view, name='Logout'),
    url(r'^admin/', admin.site.urls)
]

finalproject/menu/urls.py
from django.conf.urls import url
from django.conf.urls import include, url
from . import views


from .views import (
        post_delete,
        )

app_name = 'menu'
urlpatterns = [
    url(r'^$', views.viewmenu, name='viewmenu'),
    url(r'^(?P<menu_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<menu_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^post/$', views.post, name='update'),
    url(r'^post/(?P<pk>\d+)/$', views.detail, name='detail'),
    #new information here
    url(r'^new/$', views.specialviewmenu, name='specialviewmenu'),
    url(r'^postnew/$', views.specialpost, name='specialupdate'),
    url(r'^postnew/(?P<pk>\d+)/$', views.specialdetail, name='specialdetail'),
    url(r'^manager$', views.managerview, name='managerview'),
    #SUREVEY URLS
    url(r'^survey/$', views.viewsurvey, name='survey'),
    url(r'^surveynew/$', views.viewpost, name='surveyupdate'),
    url(r'^survey/(?P<question_id>[0-9]+)/$', views.viewdetail, name='surveydetail'),
]

finalproject/restaurant/urls.py
from django.conf.urls import url
from . import views

app_name = 'restaurant'
urlpatterns = [
    url(r'^$', views.home, name='home'),
	url(r'^guest-user/$', views.TableIDVerification, name='Guest User'),
	url(r'^guest-user/tryagain$', views.TryAgain, name='tryagain'),
	url(r'^order-placed/$', views.orderplaced, name='OrderPlaced'),
	url(r'^contact-server/$', views.ContactServer, name='ContactServer'),
	url(r'^contact-server-sent/$', views.ContactServerSent, name='ContactServerSent'),
    url(r'^server/$', views.ServerView.as_view(), name='server'),
    url(r'^server/orderstart$', views.StartOrder, name='orderstart'),
    url(r'^gateway/(\w+)/$', views.gateway, name='gateway'),
    url(r'^server/orders$', views.OrderView.as_view(), name='orders'),
    url(r'^server/(?P<order_id>[0-9]+)/orderdetails$', views.orderdetail, name='orderdetails'),
    url(r'^server/(?P<pk>[0-9]+)/alertdetails$', views.AlertDetailView.as_view(), name='alertdetails'),
    url(r'^(?P<alert_id>[0-9]+)/resolveAlert/$', views.resolveAlert, name='resolveAlert'),
    url(r'^kitchen/$', views.KitchenView.as_view(), name='kitchen'),
    url(r'^kitchen/kitchendetail/(?P<order_id>[0-9]+)$', views.kitchendetail, name='kitchendetail'),
	
	url(r'^order-menu/$', views.MenuView.as_view(), name='Menu'),
	url(r'^(?P<pk>[0-9]+)/additem/$', views.AddItem, name='additem'),
	url(r'^login/$', views.login_view, name='Login'),
	url(r'^server/$', views.StartOrder, name='server'),
	url(r'^server/orders$', views.OrderView.as_view(), name='orders'),
	url(r'^server/(?P<pk>[0-9]+)/orderdetails$', views.OrderDetailView.as_view(), name='orderdetails'),
    url(r'^createaccount/$', views.createaccount),
    url(r'^payment/$', views.payment, name='payment'),
]

finalproject/menu/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.db import models


class menu(models.Model):
  
    Name = models.CharField(max_length=200)
    Description = models.CharField(max_length=200)
    Nutrition = models.CharField(max_length=200)
    Price = models.IntegerField(default=170)
class specialmenu(models.Model):
    Name = models.CharField(max_length=200)
    Description = models.CharField(max_length=200)
    Nutrition = models.CharField(max_length=200)
    Price = models.IntegerField(default=170)
class survey(models.Model):
    question = models.CharField(max_length=200)
    score = models.IntegerField(default=0)
class choice(models.Model):
    question = models.ForeignKey(survey, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    

finalproject/menu/forms.py
from django import forms
from .models import menu
from .models import specialmenu
from .models import survey

class UserForm(forms.ModelForm):
    class Meta:
        model = menu
        fields = ['Name', 'Description','Nutrition', 'Price']
class specialUserForm(forms.ModelForm):
    class Meta:
        model = specialmenu
        fields = ['Name', 'Description','Nutrition', 'Price']
class customersurvey(forms.ModelForm):
    class Meta:
        model = survey
        fields = ['question', 'score']

finalproject/menu/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.template import loader
from django.http import Http404
from django.shortcuts import get_object_or_404, render

# Create your views here.
from django.http import HttpResponse
from .models import menu
from .models import specialmenu
from .forms import specialUserForm
import datetime

def viewmenu(request):
    latest_menu_list = menu.objects.order_by('-id')[:1000]
    template = loader.get_template('menu/index.html')
    context = {
        'latest_menu_list': latest_menu_list,
    	}
    return HttpResponse(template.render(context, request))
    
def detail(request, menu_id):
    question = get_object_or_404(menu, pk=menu_id)
    return render(request, 'menu/detail.html', {'question': question})


def results(request, menu_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % menu_id)

def display(request):
  return render_to_response('index.html', {'obj': models.menu.objects.all()})

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import View
from .models import menu as Users
from .forms import UserForm
from django.shortcuts import redirect
from .models import menu


def post(request):
        
        if request.method == "POST":
                form = UserForm(request.POST)
                if form.is_valid():
                    latest_menu_list = menu.objects.order_by('-id')[:1000]
                    post = form.save(commit=False)
                    post.save()
                    context ={'latest_menu_list': latest_menu_list,}
                    return render(request, "menu/index.html",context)
        else:
                form = UserForm()
                
        return render(request, 'menu/update.html', {'form': form})
        
    
        
def post_delete(request, menu_id):
        instance=get_object_or_404(menu, pk=menu_id)
        instance.deleted()
        messages.success(request, "succesfully deleted")
        #return redirect('detail',pk=post.pk)


### SPECIAL MENU CODE SECTION

def specialviewmenu(request):
    latest_menu_list = specialmenu.objects.order_by('-id')[:1000]
    template = loader.get_template('menu/specialindex.html')
    context = {
        'latest_menu_list': latest_menu_list,
        }
    return HttpResponse(template.render(context, request))
    
def specialdetail(request, menu_id):
    question = get_object_or_404(menu, pk=_id)
    return render(request, 'menu/specialdetail.html', {'question': question})


def specialresults(request, menu_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % menu_id)

def specialdisplay(request):
  return render_to_response('specialindex.html', {'obj': models.specialmenu.objects.all()})

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import View
from .models import menu as Users
from .forms import UserForm
from django.shortcuts import redirect
from .models import menu


def specialpost(request):
        
        if request.method == "POST":
                form = specialUserForm(request.POST)
                if form.is_valid():
                    latest_menu_list = specialmenu.objects.order_by('-id')[:1000]
                    post = form.save(commit=False)
                    post.save()
                    context ={'latest_menu_list': latest_menu_list,}
                    return render(request, "menu/specialindex.html",context)
        else:
                form = specialUserForm()
                
        return render(request, 'menu/specialupdate.html', {'form': form})
        
    
        
def specialpost_delete(request, menu_id):
        instance=get_object_or_404(menu, pk=menu_id)
        instance.deleted()
        messages.success(request, "succesfully deleted")
        #return redirect('detail',pk=post.pk)

#    response = "You're looking at the results of question %s."
#    return HttpResponse(response % menu_id)

#open dashboard for manager
def managerview(request):
    template = loader.get_template('menu/welcome.html')
    return render(request, "menu/welcome.html", {'time' : datetime.datetime.now()})

## CUSTOMER SURVEYYY##############

from .models import survey
from .forms import customersurvey
def viewsurvey(request):
    latest_menu_list1 = survey.objects.order_by('-id')[:1000]
    template = loader.get_template('menu/survey.html')
    context = {
        'latest_menu_list1': latest_menu_list1,
        }
    return HttpResponse(template.render(context, request))
    
def viewdetail(request, menu_id):
    question = get_object_or_404(menu, pk=menu_id)
    return render(request, 'menu/surveydetail.html', {'question': question})


def viewresults(request, menu_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % menu_id)

def viewdisplay(request):
  return render_to_response('survey.html', {'obj': models.menu.objects.all()})

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import View
from .models import menu as Users
from .forms import UserForm
from django.shortcuts import redirect
from .models import menu


def viewpost(request):
        
        if request.method == "POST":
                form = customersurvey(request.POST)
                if form.is_valid():
                    latest_menu_list = survey.objects.order_by('-id')[:1000]
                    post = form.save(commit=False)
                    post.save()
                    context ={'latest_menu_list1': latest_menu_list,}
                    return render(request, "menu/survey.html",context)
        else:
                form = customersurvey()
                
        return render(request, 'menu/surveyupdate.html', {'form': form})
        
    
        
def post_delete(request, menu_id):
        instance=get_object_or_404(menu, pk=menu_id)
        instance.deleted()
        messages.success(request, "succesfully deleted")
        #return redirect('detail',pk=post.pk)

finalproject/menu/templates/menu/detail.html
{% extends 'menu/managerbase.html' %}
{% load static %}
{% block content %}
<div class="row">
<div class="col-md-4">
  <div class="card">
    <div class="card-header card-header-icon" data-background-color="grey">
      <i class="material-icons">restaurant_menu</i>
    </div>
    <div class="card-content">
      <h4 class="card-title">{{ question.Name }}</h4>
      <h3>Description: {{ question.Description }}</h3>
      <h3>Nutrition: {{ question.Nutrition }}</h3>
      <h3>Price: $ {{ question.Price }}</h3>
    </div>
  </div>
</div>
</div>
{% endblock %}

finalproject/menu/templates/menu/index.html
{% extends 'menu/managerbase.html' %}
{% load static %}
{% block content %}
<div class="row">
<div class="col-md-12">
  <div class="card">
    <div class="card-header card-header-icon" data-background-color="blue">
      <i class="material-icons">restaurant_menu</i>
    </div>
    <div class="card-content">
      <h4 class="card-title">Current Menu</h4>
      {% if latest_menu_list %}
        <div class="table-responsive">
          <table class="table">
            <thead class="text-primary">
              <th>Item Name</th>
              <th>Description</th>
	             <th>Nutrition</th>
	              <th>Price</th>
            </thead>
            <tbody>
              {% for menu in latest_menu_list %}
                <tr>
                    <td><a href="/menu/{{ menu.id }}/">{{menu.Name}}</a></td>
                    <td>{{menu.Description}}</td>
	                  <td>{{menu.Nutrition}}</td>
	                  <td>$ {{menu.Price}}</td>
                </tr>
              {% endfor %}
        </tbody>
      </table>
      {% else %}
            <p>What?! You have a empty Menu, please add food to it now!</p>
      {% endif %}

        <div class=a><a href="{% url 'menu:update' %}">+ New Menu item</a></div>
        </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

finalproject/menu/templates/menu/managerbase.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Dashboard</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <!-- Bootstrap core CSS     -->
    <link  rel="stylesheet" type="text/css" href="{% static "restaurant/css/bootstrap.min.css" %}"/>
    <!--  Material Dashboard CSS    -->
    <link  rel="stylesheet" type="text/css" href="{% static "restaurant/css/material-dashboard.css" %}"/>
    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons" />
</head>

<body>
{% if user.is_authenticated %}
<div class="wrapper">
    <div class="sidebar" data-active-color="rose" data-background-color="black">
        <div class="logo">
            <a href="{% url 'restaurant:home' %}" class="simple-text">
                Raccoon Express
            </a>
        </div>
        <div class="logo logo-mini">
            <a href="{% url 'restaurant:home' %}" class="simple-text">
                Home
            </a>
        </div>
        <div class="sidebar-wrapper">
            <div class="user">
                <div class="photo">
                    <img src="{% static "restaurant/img/faces/avatar.jpg" %}" />
                </div>
                <div class="info">
                    <a data-toggle="collapse" href="#collapseExample" class="collapsed">
                        {{ username }}
                        <b class="caret"></b>
                    </a>
                    <div class="collapse" id="collapseExample">
                        <ul class="nav">
                            <li>
                                <a href="#">My Profile</a>
                            </li>
                            <li>
                                <a href="#">Edit Profile</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <ul class="nav">
              <li class="active">
                  <a href="{% url 'menu:managerview' %}">
                      <i class="material-icons">supervisor_account</i>
                      <p>Manager</p>
                  </a>
              </li>
            </ul>

        </div>
    </div>
    <div class="main-panel">
        <nav class="navbar navbar-transparent navbar-absolute">
            <div class="container-fluid">
                <div class="navbar-minimize">
                    <button id="minimizeSidebar" class="btn btn-round btn-white btn-fill btn-just-icon">
                        <i class="material-icons visible-on-sidebar-regular">more_vert</i>
                        <i class="material-icons visible-on-sidebar-mini">view_list</i>
                    </button>
                </div>
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"> . </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="material-icons">notifications</i>
                                <span class="notification">{{current_alert_list.count}}</span>
                                <p class="hidden-lg hidden-md">
                                    Notifications
                                    <b class="caret"></b>
                                </p>
                            </a>
                            <ul class="dropdown-menu">
                              {% if current_alert_list %}
                                  {% for alert in current_alert_list %}
                                  <li><a href="{% url 'restaurant:alertdetails' alert.id %}">Table #{{ alert.Order.Table }} - {{alert.Message}}</a></li>
                                  {% endfor %}
                              {% else %}
                                  <li><a href="">No current alerts</a></li>
                              {% endif %}
                            </ul>
                        </li>

                        <li "dropdown">
                            <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="material-icons">person</i>
                                <p class="hidden-lg hidden-md">Profile</p>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="/logout">Sign Out</a>
                                </li>
                            </ul>
                        </li>

                        <li class="separator hidden-lg hidden-md"></li>
                    </ul>
                    <form class="navbar-form navbar-right" role="search">
                        <div class="form-group form-search is-empty">
                            <input type="text" class="form-control" placeholder="Search">
                            <span class="material-input"></span>
                        </div>
                        <button type="submit" class="btn btn-white btn-round btn-just-icon">
                            <i class="material-icons">search</i>
                            <div class="ripple-container"></div>
                        </button>
                    </form>
                </div>
            </div>
        </nav>


<!--Main Content starts here -->

        <div class="content">
          <div class="header text-center">
            <h3 class = "title">Welcome back Manager!</h3>
          </div>
            <div class="container-fluid">
              {% block content %}
              {% endblock %}
          </div>
        </div>


        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>
                        <li>
                            <a href="/">
                                Home
                            </a>
                        </li>
                        <li>
                            <a href="#">
                               About Us
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'menu:managerview' %}">
                               Manager DashBoard
                            </a>
                        </li>
                </nav>
                <p class="copyright pull-right">
                    &copy;
                    <script>
                        document.write(new Date().getFullYear())
                    </script>
                    Made by the most awesome Group 4
                </p>
            </div>
        </footer>
    </div>
</div>
  {% else %}
    <h1><a href="/login">Please Login</a></h1>
  {% endif %}
</body>

<!--   Core JS Files   -->
<script src="{% static "restaurant/js/jquery-3.1.1.min.js" %}" type="text/javascript"></script>
<script src="{% static "restaurant/js/jquery-ui.min.js" %}" type="text/javascript"></script>
<script src="{% static "restaurant/js/bootstrap.min.js" %}" type="text/javascript"></script>
<script src="{% static "restaurant/js/material.min.js" %}" type="text/javascript"></script>
<script src="{% static "restaurant/js/perfect-scrollbar.jquery.min.js" %}" type="text/javascript"></script>
<!-- Forms Validations Plugin -->
<script src="{% static "restaurant/js/jquery.validate.min.js" %}"></script>
<!--  Plugin for Date Time Picker and Full Calendar Plugin-->
<script src="{% static "restaurant/js/moment.min.js" %}"></script>
<!--  Charts Plugin -->
<script src="{% static "restaurant/js/chartist.min.js" %}"></script>
<!--  Plugin for the Wizard -->
<script src="{% static "restaurant/js/jquery.bootstrap-wizard.js" %}"></script>
<!--  Notifications Plugin    -->
<script src="{% static "restaurant/js/bootstrap-notify.js" %}"></script>
<!-- DateTimePicker Plugin -->
<script src="{% static "restaurant/js/bootstrap-datetimepicker.js" %}"></script>
<!-- Vector Map plugin -->
<script src="{% static "restaurant/js/jquery-jvectormap.js" %}"></script>
<!-- Sliders Plugin -->
<script src="{% static "restaurant/js/nouislider.min.js" %}"></script>
<!--  Google Maps Plugin    -->
<script src="https://maps.googleapis.com/maps/api/js"></script>
<!-- Select Plugin -->
<script src="{% static "restaurant/js/jquery.select-bootstrap.js" %}"></script>
<!--  DataTables.net Plugin    -->
<script src="{% static "restaurant/js/jquery.datatables.js" %}"></script>
<!-- Sweet Alert 2 plugin -->
<script src="{% static "restaurant/js/sweetalert2.js" %}"></script>
<!--	Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
<script src="{% static "restaurant/js/jasny-bootstrap.min.js" %}"></script>
<!--  Full Calendar Plugin    -->
<script src="{% static "restaurant/js/fullcalendar.min.js" %}"></script>
<!-- TagsInput Plugin -->
<script src="{% static "restaurant/js/jquery.tagsinput.js" %}"></script>
<!-- Material Dashboard javascript methods -->
<script src="{% static "restaurant/js/material-dashboard.js" %}"></script>
<!-- Material Dashboard DEMO methods, don't include it in your project! -->
<script src="{% static "restaurant/js/demo.js" %}"></script>
<script src="{% static "restaurant/js/racconcustom.js" %}"></script>

</html>

finalproject/menu/templates/menu/specialdetail.html
<h1> Menu Information </h1>
<h3>Name:{{ question.Name }}</h3>
<h3>Description:{{ question.Description }}</h3>
<h3>Nutrition:{{ question.Nutrition }}</h3>
<h3>Price:{{ question.Price }}</h3>

finalproject/menu/templates/menu/specialindex.html
{% extends 'menu/managerbase.html' %}
{% load static %}
{% block content %}
<div class="row">
<div class="col-md-12">
  <div class="card">
    <div class="card-header card-header-icon" data-background-color="green">
      <i class="material-icons">folder_special</i>
    </div>
    <div class="card-content">
      <h4 class="card-title">Current Menu</h4>
      {% if latest_menu_list %}
        <div class="table-responsive">
          <table class="table">
            <thead class="text-primary">
              <th>Item Name</th>
              <th>Description</th>
	             <th>Nutrition</th>
	              <th>Price</th>
            </thead>
            <tbody>
              {% for menu in latest_menu_list %}
                <tr>
                    <td><a href="/menu/{{ menu.id }}/">{{menu.Name}}</a></td>
                    <td>{{menu.Description}}</td>
	                  <td>{{menu.Nutrition}}</td>
	                  <td>$ {{menu.Price}}</td>
                </tr>
              {% endfor %}
        </tbody>
      </table>
      {% else %}
            <p>What?! You have a empty Menu, pleace add food to it now!</p>
      {% endif %}

        <div><a href="{% url 'menu:specialupdate' %}">+ New Special Menu item</a></div>
        </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

finalproject/menu/templates/menu/specialupdate.html
{% extends 'menu/managerbase.html' %}
{% load static %}
{% block content %}


  <div class = "row"> <!-- row 1 S-->

  	<div class="col-md-4 col-md-offset-6"> <!-- card 1 S-->
    	<div class="card">
        <div class="card-header card-header-icon" data-background-color="green">
            <i class="material-icons">folder_special</i>
        </div>
        <div class="card-content">
						<h4 class="cardtitle">Add to Special Menu</h4>
						<form method = "post" action = ".">
							{% csrf_token %}
							{{ form.as_p }}
							<input class="btn btn-primary" type = "submit" value = "Submit"/>
						</form>
        </div>
      </div>
    </div> <!-- card 1 E-->

</div><!-- row 1 E-->
{% endblock %}

finalproject/menu/templates/menu/survey.html
{% extends 'menu/managerbase.html' %}
{% load static %}
{% block content %}
<div class="row">
<div class="col-md-12">
  <div class="card">
    <div class="card-header card-header-icon" data-background-color="red">
      <i class="material-icons">description</i>
    </div>
    <div class="card-content">
      <h4 class="card-title">Current Survey Questions</h4>
      {% if latest_menu_list1 %}
        <div class="table-responsive">
          <table class="table">
            <thead class="text-primary">
              <th>Question</th>
              <th>Survey Score(1-10)</th>
            </thead>
            <tbody>
              {% for survey in latest_menu_list1 %}
                <tr>
                  <td><a href="/menu/{{ survey.id }}/">{{survey.question}} </a> </td>
                  <td>{{survey.score}}</td>
                </tr>
              {% endfor %}
        </tbody>
      </table>
      {% else %}
            <<p>No Survey Update.</p>
      {% endif %}
        </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

finalproject/menu/templates/menu/surveydetail.html
<h1>{{ survey.question }}</h1>
<ul>
{% for choice in survey.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>



{% extends 'menu/managerbase.html' %}
{% load static %}
{% block content %}
<div class="row">
<div class="col-md-4">
  <div class="card">
    <div class="card-header card-header-icon" data-background-color="grey">
      <i class="material-icons">restaurant_menu</i>
    </div>
    <div class="card-content">
      <h4 class="card-title">{{ survey.question }}</h4>
      {% for choice in survey.choice_set.all %}
          <li>{{ choice.choice_text }}</li>
      {% endfor %}
    </div>
  </div>
</div>
</div>
{% endblock %}

finalproject/menu/templates/menu/surveyupdate.html
{% extends 'menu/managerbase.html' %}
{% load static %}
{% block content %}

  <div class = "row"> <!-- row 1 S-->

  	<div class="col-md-4 col-md-offset-4"> <!-- card 1 S-->
    	<div class="card">
        <div class="card-header card-header-icon" data-background-color="red">
            <i class="material-icons">description</i>
        </div>
        <div class="card-content">
						<h4 class="cardtitle">Survey Question</h4>
						<form method = "post" action = ".">
							{% csrf_token %}
							{{ form.as_p }}
							<input class="btn btn-primary" type = "submit" value = "Submit"/>
						</form>
        </div>
      </div>
    </div> <!-- card 1 E-->

</div><!-- row 1 E-->
{% endblock %}

finalproject/menu/templates/menu/welcome.html
{% extends 'menu/managerbase.html' %}
{% load static %}
{% block content %}

<!--Main Content starts here -->

              <div class = "row"> <!-- row 1 S-->

                <div class="col-md-4 col-md-offset-1"> <!-- card 1 S-->
                  <div class="card">
                    <div class="card-header card-header-icon" data-background-color="blue">
                      <i class="material-icons">restaurant_menu</i>
                    </div>
                    <div class="card-content">
                      <h4>Menu Items</h4>
                        <a class="btn btn-primary" href="{% url 'menu:viewmenu' %}">View</a>
                        <a class="btn btn-primary" href="{% url 'menu:update' %}">Add</a>
                    </div>
                  </div>
                </div> <!-- card 1 E-->

                <div class="col-md-4 col-md-offset-1"> <!-- card 2 S-->
                  <div class="card">
                    <div class="card-header card-header-icon" data-background-color="green">
                      <i class="material-icons">folder_special</i>
                    </div>
                    <div class="card-content">
                      <h4 >Special Menu Items</h4>
                        <a class="btn btn-primary" href="{% url 'menu:specialviewmenu' %}">View</a>
                        <a class="btn btn-primary" href="{% url 'menu:specialupdate' %}">Add</a>
                     </div>
                  </div>
                </div> <!-- card 2 E-->
                </div><!-- row 1 E-->

                <div class = "row"> <!-- row 2 S-->
                <div class="col-md-6 col-md-offset-3"> <!-- card 3 S-->
                  <div class="card">
                    <div class="card-header card-header-icon" data-background-color="red">
                      <i class="material-icons">description</i>
                    </div>
                    <div class="card-content">
                      <h4 >Manage Survey</h4>
                        <a class="btn btn-primary" href="{% url 'menu:survey' %}">Pre-View</a>
                        <a class="btn btn-primary" href="{% url 'menu:surveyupdate' %}">Edit Questions</a>
                     </div>
                  </div>
                </div> <!-- card 3 E-->
              </div><!-- row 2 E-->

              <div class = "row"> <!-- row 3 S-->
              <div class="col-md-4 col-md-offset-1"> <!-- card 4 S-->
                <div class="card card-stats">
                  <div class="card-header" data-background-color="rose">
                    <i class="material-icons">store</i>
                  </div>
                  <div class="card-content">
                    <p class="category">Revenue</p>
                    <h3 class="card-title"> $30,382</h3>
                   </div>
                </div>
              </div> <!-- card 4 E-->

              <div class="col-md-4 col-md-offset-1"> <!-- card 5 S-->
                <div class="card card-stats">
                  <div class="card-header" data-background-color="orange">
                    <i class="material-icons">today</i>
                  </div>
                  <div class="card-content">
                    <p class="category">Total Order</p>
                    <h3 class="card-title">52</h3>
                   </div>
                </div>
              </div> <!-- card 5 E-->

            </div><!-- row 3 E-->

{% endblock %}